upload report

diff --git a/.github/workflows/java_on_demand.yml b/.github/workflows/java_on_demand.yml
--- a/.github/workflows/java_on_demand.yml
+++ b/.github/workflows/java_on_demand.yml
@@ -52,8 +52,16 @@ jobs:
         working-directory: mock-java-app
         env:
           NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
-        run: mvn org.owasp:dependency-check-maven:check
+        run: | 
+          mvn org.owasp:dependency-check-maven:check || echo "⚠️ Dependency check failed (allowed to proceed)"
         continue-on-error: true
+
+      - name: Cache OWASP Dependency-Check data
+        if: ${{ inputs.run_scan }}
+        uses: actions/cache@v3
+        with:
+          path: ~/.dependency-check/data
+          key: ${{ runner.os }}-owasp-data-${{ hashFiles('mock-java-app/pom.xml') }}
 
 
   deploy:
